# URL del servidor de la universidad
sonar.host.url=https://sonarqube.inf.uct.cl

# Identificadores del proyecto
sonar.projectKey=omnitech-erp-ecommerce
sonar.projectName=OmniTech ERP & E-Commerce
sonar.projectVersion=1.0

# Carpetas a analizar (Basado en tu estructura de VS Code)
sonar.sources=omnitech
sonar.tests=omnitech/tests
sonar.language=py
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8

# Excluir archivos que ensucian las metricas (migraciones y scripts de carga)
sonar.exclusions=**/migrations/**, omnitech/tests/**, manage.py, populate_db.py

# Ruta al reporte de cobertura que genera "make test-ci"
sonar.python.coverage.reportPaths=coverage.xml
# Archivos tecnicos o legacy que no representan logica de negocio a medir en cobertura
sonar.coverage.exclusions=**/migrations/**,**/tests/**,omnitech/admin.py,omnitech/settings.py,omnitech/wsgi.py,omnitech/views.py,manage.py,populate_db.py
