# Generated by Django 4.2.29 on 2026-04-06 20:02

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(editable=False, help_text='Código único de seguimiento', max_length=20, unique=True)),
                ('email_invitado', models.EmailField(blank=True, help_text='Email para guest checkout (RN-06)', max_length=254, null=True)),
                ('estado', models.CharField(choices=[('pendiente_pago', 'Pendiente de Pago'), ('pagado_procesando', 'Pagado - Procesando'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente_pago', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('region_envio', models.CharField(blank=True, help_text='Región para cálculo de envío subsidiado (RN-04)', max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario registrado (null para guest checkout RN-06)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('sku', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='SKU debe contener solo mayúsculas, números y guiones', regex='^[A-Z0-9-]+$')])),
                ('categoria', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('agotado', 'Agotado')], default='activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso en kilogramos', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock_fisico', models.PositiveIntegerField(default=0, help_text='Cantidad disponible en bodega')),
                ('stock_reservado', models.PositiveIntegerField(default=0, help_text='Cantidad reservada durante checkout (RN-03)')),
                ('umbral_minimo', models.PositiveIntegerField(default=10, help_text='Nivel que dispara reabastecimiento (RN-05)')),
                ('proveedor', models.CharField(blank=True, max_length=255)),
                ('ubicacion_bodega', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Producto Físico',
                'verbose_name_plural': 'Productos Físicos',
                'db_table': 'physical_products',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='RUT debe tener formato XX.XXX.XXX-X', regex='^\\d{7,8}-[\\dkK]$')])),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('direccion', models.TextField(blank=True)),
                ('newsletter', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_compra', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='DigitalLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('sku', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='SKU debe contener solo mayúsculas, números y guiones', regex='^[A-Z0-9-]+$')])),
                ('categoria', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('agotado', 'Agotado')], default='activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('clave_encriptada', models.CharField(help_text='Clave almacenada encriptada', max_length=500)),
                ('plataforma', models.CharField(help_text='Plataforma o servicio asociado', max_length=100)),
                ('duracion_dias', models.PositiveIntegerField(default=365, help_text='Vigencia en días (0 = indefinida)')),
                ('estado_licencia', models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('consumida', 'Consumida')], default='disponible', max_length=20)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licencias_entregadas', to='omnitech.order')),
            ],
            options={
                'verbose_name': 'Licencia Digital',
                'verbose_name_plural': 'Licencias Digitales',
                'db_table': 'digital_licenses',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('licencia', models.ForeignKey(blank=True, help_text='Relación para licencias digitales', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='omnitech.digitallicense')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='omnitech.order')),
                ('producto_fisico', models.ForeignKey(blank=True, help_text='Relación para productos físicos', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='omnitech.physicalproduct')),
            ],
            options={
                'db_table': 'order_items',
                'indexes': [models.Index(fields=['pedido'], name='order_items_pedido__456b45_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('cantidad__gte', 1)), name='orderitem_cantidad_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('producto_fisico__isnull', False), ('licencia__isnull', False), _connector='OR')), name='orderitem_producto_required'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('producto_fisico__isnull', True), ('licencia__isnull', True), _connector='OR')), name='orderitem_exclusive_product'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['numero_pedido'], name='orders_numero__ac692e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['estado', 'fecha_creacion'], name='orders_estado_c5d0c7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['usuario', 'fecha_creacion'], name='orders_usuario_8b6ee0_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('subtotal__gte', 0)), name='order_subtotal_positive'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('costo_envio__gte', 0)), name='order_envio_positive'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('total__gte', 0)), name='order_total_positive'),
        ),
        migrations.AddIndex(
            model_name='digitallicense',
            index=models.Index(fields=['estado_licencia'], name='digital_lic_estado__891949_idx'),
        ),
        migrations.AddIndex(
            model_name='digitallicense',
            index=models.Index(fields=['plataforma'], name='digital_lic_platafo_7b5d7e_idx'),
        ),
    ]
