# Generated by Django 4.2.29 on 2026-04-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnitech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitallicense',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL de imagen del producto', max_length=500),
        ),
        migrations.AddField(
            model_name='physicalproduct',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL de imagen del producto', max_length=500),
        ),
    ]
