# Generated by Django 4.2.29 on 2026-04-12 02:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnitech', '0002_digitallicense_imagen_url_physicalproduct_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='RUT debe tener formato XX.XXX.XXX-X', regex='^\\d{7,8}-[\\dkK]$')]),
        ),
    ]
